### ISSUE TITLE
Bug in calculate_moller_hetero?

### ISSUE THREAD

**Issue by mdkarcher** [mdkarcher/phylodyn#7]
@JuliaPalacios  @vnminin 

I think I have found a bug in the function calculate_moller_hetero. Suppose we have a simple phylogeny,
s_times = 0
n_sampled = 4
coal_times = c(0.25, 0.75, 1.0)
with grid = c(0.0, 0.5, 1.0).

What gets passed to inla looks like
time2 = c(0.25, 0.75, 0.75)
event_new2 = c(0, 1, 1)
E_factor2 = c(2.25, 0.75, 0.25)
but this only has two coalescent events, and no coalescent event linked to the 0.25 time point.

I believe it should look more like
time = c(0.25, 0.25, 0.75, 0.75)
event = c(1, 0, 1, 1)
E = c(1.50, 0.75, 0.75, 0.25)
and I'm working on some vectorized code that will replicate this.

I think the bug happens here in calculate_moller_.hetero:
where <- 1
...
event_new <- c(event_new,event[(where):(where+count-1)])
...
event_new <- c(event_new,event[where])

Because the first event is a sampling event that never ends an interval (proceeding as the function does from the present into the past), it gets prepended to the event_new vector. Since event_new has to match up with the time vector, this pushes each coalescent event forward by one and removes the last coalescent event.

@JuliaPalacios would you take a look at the code and see if my reasoning is sound? I'm going to push an experimental revision to calculate_moller_hetero today or tomorrow for comparison.

**Comment by JuliaPalacios** [comment]
Hi Mke,

Yes, I am sure this "hetero" should fail for "iso". There should be a function for isochronous or a wrapper that detects whether it is iso or heterochronous? 

What do you think?

**Comment by JuliaPalacios** [comment]
and sure! I'll be happy to test it

**Comment by mdkarcher** [comment]
Hmm, I'm not sure I agree. Isochronous sampling is a special case of heterochronous sampling, so if it doesn't work for iso it shouldn't work for hetero. Extending the example to be hetero,
s_times = c(0, 1.25)
n_sampled = c(4, 1)
coal_times = c(0.25, 0.75, 1.0, 1.5)
with grid = c(0.0, 0.5, 1.0, 1.5).

We see calculate_moller_hetero passes to INLA:
time2 = c(0.25, 0.75, 0.75, 1.25, 1.25)
event_new2 = c(0, 1, 1, 1, 0)
E_factor2 = c(2.25, 0.75, 0.25, 0.00, 0.25)
which still does not have the events corresponding to the right time points.

I've pushed an experimental version of calculate_moller_hetero which, I believe, should work for iso and hetero.

**Comment by JuliaPalacios** [comment]
Hi Mike! Cool! thanks

**Comment by JuliaPalacios** [comment]
Hey Mike,

Here is another proposal:
init <- coal_lik_init(samp_times=samp_times, n_sampled=n_sampled, 
                      coal_times=coal_times, grid=grid)
ind <- 1:(init$ng)
ind_rep = rep(ind, init$gridrep)
#init$gridrep includes coalescent times and sampling times
E_expanded = init$D * init$C
E <-  as.vector(tapply(E_expanded, ind_rep, sum)) #calculates the joint over grid points
y <- as.vector(tapply(init$y, ind_rep, sum)) 
data.inla<-data.frame(y=y,time=midpts,E=log(E))
formula.inla=y~-1+f(time,model="rw1",hyper = list(prec = list(param = c(.001, .001))),constr=FALSE)
res_INLA<-inla(formula.inla,family="poisson",data=data.inla,offset=E,control.predictor=list(compute=TRUE))

**Comment by JuliaPalacios** [comment]
Hey Mike

So, the thing is that now that I am playing with INLA I realized that any "constant" factor in the likelihood is not important for INLA so it would be the same to use for example (many exponentials) or one poisson, etc. So in the previous example, I am just summing the coalescent events (y) in the grid intervals and it works :), so I think this version is simpler. Doing the same for the preferential sampling one, I get this:
calculate.pref3<-function (samp_times=samp_times, n_sampled=n_sampled, 
                           coal_times=coal_times, lengthout, prec_alpha = 0.01, 
                           prec_beta = 0.01, beta1_prec = 0.001, E.log.zero = -100, 
                           alpha = NULL, beta = NULL) 
  #Updated by Julia, August 11, 2015
{
  if (prec_alpha == 0.01 & prec_beta == 0.01 & !is.null(alpha) & 
      !is.null(beta)) {
    prec_alpha = alpha
    prec_beta = beta
  }
  all_times <- sort(c(samp_times, coal_times));
  grid <- seq(0, max(all_times), length.out = lengthout)
  midpts <- grid[-1] - diff(grid)/2
  init <- coal_lik_init(samp_times=samp_times, n_sampled=n_sampled, 
                        coal_times=coal_times, grid=grid)
  ##For the coalescent part
  ind <- 1:(init$ng)
  ind_rep = rep(ind, init$gridrep)
  E_expanded = init$D * init$C
  E<-as.vector(tapply(E_expanded, ind_rep, sum))
  E.log <-  log(E) #calculates the joint over grid points
  E.log[E==0]<-E.log.zero
  
  y <- as.vector(tapply(init$y, ind_rep, sum)) 
  
  #for the sampling times
  ns <- length(samp_times)
  new_samp_times<-rep(0,length(grid)-1)
  for (j in 2:length(grid)){
    new_samp_times[(j-1)]<-sum(n_sampled[samp_times>grid[j-1] & samp_times<=grid[j]])
  }
  new_samp_times[1]<-new_samp_times[1]+1
  
  miss<-sum(grid>max(samp_times)) #treat the counts (null) beyond the oldest sampling time as missing data
  
  n1 <- init$ng
  n2 <- init$ng-miss+1

  Y <- matrix(NA, n1 + n2, 2)
  beta0 <- c(rep(0, n1), rep(1, n2))
  newE <- rep(NA, n1 + n2)
  newE[1:n1] <- E.log
  newE[(n1 + 1):(n1 + n2)] <- log(diff(grid))[1:(init$ng-miss+1)]
  megafield <- c(midpts, midpts[1:(init$ng-miss+1)])
  Y[1:n1, 1] <- y
  Y[(n1 + 1):(n2 + n1), 2] <- new_samp_times[1:(init$ng-miss+1)]
  #  r <- c(rep(1, n1), rep(2, n2))
  w <- c(rep(1, n1), rep(-1, n2))
  ii <- c(midpts, rep(NA, n2))
  jj <- c(rep(NA, n1), midpts[1:(init$ng-miss+1)])
  formula.pref <- Y ~ -1 + beta0 + f(ii, model = "rw1", hyper = list(prec = list(param = c(prec_alpha, 
                                                                                           prec_beta))), constr = FALSE) + f(jj, w, copy = "ii", 
                                                                                                                             fixed = FALSE, param = c(0, beta1_prec))
  data.pref <- list(Y = Y, beta0 = beta0, ii = ii, jj = jj, 
                    E = newE, w = w)
  mod.pref <- INLA::inla(formula.pref, family = c("poisson", 
                                                  "poisson"), offset = E, data = data.pref, control.predictor = list(compute = TRUE))
  return(list(result = mod.pref, grid = grid))
}

**Comment by vnminin** [comment]
@JuliaPalacios and @mdkarcher. So was there a bug or not? We need to know if we need to re-run everything from scratch.

**Comment by JuliaPalacios** [comment]
Hi mike and Vladimir,
I doubt we would need to rerun everything but I could check what and what not needs to be re-run. Mike? Can you add your scripts for the paper?
Julia

**Comment by mdkarcher** [comment]
I pushed my new versions of calculate_* (infer_coal, infer_samp, and infer_coal_samp). I included an option to use n_sampled in the samp functions. They all appear to be working, but I still need to quantify how much the changes have affected our results.

**Comment by vnminin** [comment]
@mdkarcher and @JuliaPalacios, I still don't see an agreement among us whether Mike had found a real bug or not. Mike thinks that the vectors that correspond to "data" were misaligned when they were passed to inla. It would be nice if Julia could confirm that or explicitly disagree with Mike :)

**Comment by JuliaPalacios** [comment]
I assumed that coalescent times are different than sampling times and
different than grid times. I have never run into a problem with the
function as it was but I can see how there might be a case where this fails
like the example Mike shows.  I didn't have the problem for the influenza
data or for the simulations used in Shiwei's papers. Does it impact the
"preferential sampling paper"? I don't know. I don't have access to the
scripts yet.


On Thu, Aug 13, 2015 at 2:44 PM, Vladimir N. Minin <notifications@github.com

**Comment by vnminin** [comment]
Rambaut's data analysis is affected, but not in a major way. @mdkarcher should be able to give you an example illustrating the difference.

**Comment by JuliaPalacios** [comment]
Hello!
There is no difference for Rambaut's data. Perhaps you are confounding the bug for sampling times? Ok, so I looked in detail to the new code that Mike is adding. All the enhancements seem very useful! Cool! With respect to "my bug" I insist that that should not impact unless you have the special case that Mike already solved. I added some files to the repository but the important I would like @vnminin to check is the Revision_INLA_Functions.pdf.

**Comment by vnminin** [comment]
Thanks, @JuliaPalacios! 

Not sure what to make of it, because @mdkarcher  has shown me a similar comparison with results being different for Rambaut's data. Mike, could you add your code to Julia's Revision_INLA_Functions.Rnw file?

We have been looking at preferential bug separately and yes, it makes a big difference for Travor's data. This difference is welcome, because we now should have much more interesting results. So thanks for catching this bug, @JuliaPalacios!

**Comment by mdkarcher** [comment]
Ah I think I understand. @JuliaPalacios you used the BNPR function, which is currently a wrapper for the largely unaltered calculate_moller_hetero/calculate_moller_hetero_pref while I'm testing the new code. My new code is in infer_coal/infer_coal_samp. I updated the Revision_INLA_Functions.Rnw file and it shows some small pointwise differences, up at 12% in places.

**Comment by JuliaPalacios** [comment]
Hi!
Ok! I also tried "my new" version and I am also getting different things (see updated Revision_INLA_Functions.Rnw"), so I will keep digging.
Thanks for the clarification.

**Comment by JuliaPalacios** [comment]
Hey Mike! Please take a look to Revision_INLA_Function2.Rnw. I am trying to validate your new function but for some reasons, I am getting different things (not by much, but different). Can you help me figure out what is going on.

**Comment by mdkarcher** [comment]
You are using a different prior. We had settled on a Gamma(0.01, 0.01) prior on tau, but you had coded a Gamma(0.001, 0.001) prior. When I made the prior the same, the your new code and my new code plotted on top of each other.

**Comment by JuliaPalacios** [comment]
Agree! I had a typo in the heterochronous function. The new function has been tested successfully!
